[phases.setup]
nixPkgs = ["nodejs_22", "ffmpeg", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["pip install -U yt-dlp --break-system-packages", "npm ci"]

[start]
cmd = "node index.js"
